import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface": "#0f131c",
        "surface-dim": "#0f131c",
        "surface-bright": "#353943",
        "surface-container-lowest": "#0a0e17",
        "surface-container-low": "#181b25",
        "surface-container": "#1c1f29",
        "surface-container-high": "#262a34",
        "surface-container-highest": "#31353f",
        "on-surface": "#dfe2ef",
        "on-surface-variant": "#c1c6d7",
        "inverse-surface": "#dfe2ef",
        "inverse-on-surface": "#2c303a",
        "outline": "#8b90a0",
        "outline-variant": "#414754",
        "surface-tint": "#aec6ff",
        "primary": "#aec6ff",
        "on-primary": "#002e6b",
        "primary-container": "#0070f3",
        "on-primary-container": "#ffffff",
        "inverse-primary": "#0059c5",
        "secondary": "#a5e7ff",
        "on-secondary": "#003543",
        "secondary-container": "#00d2ff",
        "on-secondary-container": "#00566a",
        "tertiary": "#d0bcff",
        "on-tertiary": "#3c0091",
        "tertiary-container": "#8656f0",
        "on-tertiary-container": "#fffeff",
        "error": "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "space-xs": "0.25rem",
        "gutter": "1rem",
        "space-xl": "1.5rem",
        "space-sm": "0.5rem",
        "gutter-compact": "0.5rem",
        "margin-dock": "0.5rem",
        "space-md": "0.75rem",
        "margin": "1rem",
        "space-lg": "1rem",
      },
      fontFamily: {
        display: ["Inter", "sans-serif"],
        body: ["JetBrains Mono", "monospace"],
        mono: ["JetBrains Mono", "monospace"],
      },
    },
  },
  plugins: [],
};
export default config;
