"""Loads the Elliptic Bitcoin transaction dataset's graph structure and
derives a heuristic "exchange-deposit-like" feature signature from it.

Real dataset: https://www.kaggle.com/datasets/ellipticco/elliptic-data-set
(txId, time_step, 93 local + 72 aggregate anonymized features, edge list,
class in {1=illicit, 2=licit, unknown}). It requires a Kaggle account and
carries its own license, so it isn't bundled here. Drop the three real CSVs
(elliptic_txs_features.csv, elliptic_txs_classes.csv,
elliptic_txs_edgelist.csv) into `Blockchain/data/elliptic/` to use it as-is
-- this loader reads that exact schema. Until then it falls back to
`Blockchain/data/elliptic_sample/`, a small synthetic sample generated by
`gen_elliptic_sample.py` with the identical column schema, for development
and testing.

We don't use Elliptic's anonymized features directly as a live-chain
signature (they aren't comparable to real on-chain address features). What
we *do* borrow is its graph topology: within the labeled-licit subset, the
transactions with disproportionately high in-degree (many small inputs
consolidating into one output) are a structural proxy for deposit /
consolidation behaviour typical of custodial exchange wallets. We compute a
small reference signature (mean/std of in-degree, out-degree, and
in/out ratio for that subset) once, and Backend's scoring engine compares a
live candidate address's equivalent topology features against it.
"""
from __future__ import annotations

import csv
import os
import statistics
from dataclasses import dataclass
from functools import lru_cache

import networkx as nx

REAL_DATA_DIR = os.path.join(os.path.dirname(__file__), "data", "elliptic")
SAMPLE_DATA_DIR = os.path.join(os.path.dirname(__file__), "data", "elliptic_sample")

LICIT = "2"
ILLICIT = "1"


def _resolve_data_dir() -> str:
    required = ["elliptic_txs_features.csv", "elliptic_txs_classes.csv", "elliptic_txs_edgelist.csv"]
    if all(os.path.exists(os.path.join(REAL_DATA_DIR, f)) for f in required):
        return REAL_DATA_DIR
    return SAMPLE_DATA_DIR


@lru_cache(maxsize=1)
def load_elliptic_graph() -> nx.DiGraph:
    """Builds a directed tx-to-tx graph with a `class` attribute per node."""
    data_dir = _resolve_data_dir()
    classes_path = os.path.join(data_dir, "elliptic_txs_classes.csv")
    edgelist_path = os.path.join(data_dir, "elliptic_txs_edgelist.csv")

    graph = nx.DiGraph()

    with open(classes_path, newline="", encoding="utf-8") as fh:
        for row in csv.DictReader(fh):
            graph.add_node(row["txId"], tx_class=row["class"])

    with open(edgelist_path, newline="", encoding="utf-8") as fh:
        for row in csv.DictReader(fh):
            src, dst = row["txId1"], row["txId2"]
            if src in graph and dst in graph:
                graph.add_edge(src, dst)

    return graph


@dataclass(frozen=True)
class ExchangeSignature:
    """Reference topology signature for exchange-deposit-like transactions,
    derived from the licit/high-fan-in subset of the Elliptic graph."""

    mean_in_degree: float
    std_in_degree: float
    mean_out_degree: float
    std_out_degree: float
    mean_in_out_ratio: float
    sample_size: int


@lru_cache(maxsize=1)
def compute_exchange_signature(high_fan_in_percentile: float = 0.85) -> ExchangeSignature:
    graph = load_elliptic_graph()

    licit_nodes = [n for n, d in graph.nodes(data=True) if d.get("tx_class") == LICIT]
    if not licit_nodes:
        return ExchangeSignature(0, 0, 0, 0, 0, 0)

    in_degrees = {n: graph.in_degree(n) for n in licit_nodes}
    sorted_in = sorted(in_degrees.values())
    cutoff_idx = min(int(len(sorted_in) * high_fan_in_percentile), len(sorted_in) - 1)
    cutoff = sorted_in[cutoff_idx] if sorted_in else 0

    proxy_nodes = [n for n in licit_nodes if in_degrees[n] >= cutoff and in_degrees[n] > 0]
    if not proxy_nodes:
        proxy_nodes = licit_nodes

    in_deg_vals = [graph.in_degree(n) for n in proxy_nodes]
    out_deg_vals = [graph.out_degree(n) for n in proxy_nodes]
    ratios = [
        (graph.in_degree(n) + 1) / (graph.out_degree(n) + 1) for n in proxy_nodes
    ]

    return ExchangeSignature(
        mean_in_degree=statistics.fmean(in_deg_vals),
        std_in_degree=statistics.pstdev(in_deg_vals) or 1.0,
        mean_out_degree=statistics.fmean(out_deg_vals),
        std_out_degree=statistics.pstdev(out_deg_vals) or 1.0,
        mean_in_out_ratio=statistics.fmean(ratios),
        sample_size=len(proxy_nodes),
    )


def using_real_dataset() -> bool:
    return _resolve_data_dir() == REAL_DATA_DIR
